export default {
  status: "success",
	responseData: [{
		unitPrice: 95,
		startMonth: "2/1/2019",
		revenueType: "MRC",
		revenueRecognitionName: null,
		revenueRecognitionId: null,
		qty: 1,
		productItemName: "Captio User Delegation",
		productItemId: "a01A000001gmFXZIA2",
		productFLIId: "a2m2G000000AJKQQA4",
		priorMRR: null,
		optionItemName: null,
		optionItemId: null,
		optionFLIId: null,
		monthsVR: null,
		monthsNRC: null,
		monthsMRC: null,
		months: 18,
		displayUnitPrice: "$95.00",
		displayQty: "1",
		displayPriorMRR: null,
		committed: "No",
		attributesWithValues: null,
		attributes: null
	},
	{
		unitPrice: 55,
		startMonth: "3/1/2019",
		revenueType: "NRC",
		revenueRecognitionName: null,
		revenueRecognitionId: null,
		qty: 1,
		productItemName: "TNS Link",
		productItemId: "a01A000001utm3RIAQ",
		productFLIId: "a2m2G000009H0fHQAS",
		priorMRR: null,
		optionItemName: null,
		optionItemId: null,
		optionFLIId: null,
		monthsVR: null,
		monthsNRC: null,
		monthsMRC: null,
		months: 12,
		displayUnitPrice: "$55.00",
		displayQty: "1",
		displayPriorMRR: null,
		committed: "No",
		attributesWithValues: null,
		attributes: null
	},
	{
		unitPrice: 100,
		startMonth: "2/1/2019",
		revenueType: "MRC",
		revenueRecognitionName: null,
		revenueRecognitionId: null,
		qty: 1,
		productItemName: "TNS Link",
		productItemId: "a01A000001utm3RIAQ",
		productFLIId: "a2m2G000009H0fIQAS",
		priorMRR: null,
		optionItemName: null,
		optionItemId: null,
		optionFLIId: null,
		monthsVR: null,
		monthsNRC: null,
		monthsMRC: null,
		months: 24,
		displayUnitPrice: "$100.00",
		displayQty: "1",
		displayPriorMRR: null,
		committed: "No",
		attributesWithValues: null,
		attributes: null
	}],
	message: null
}
